const blurbs = {
    savings: "Savings are assumed to be put into broad index funds accruing an average of 7% annual interest. Although equity has no guaranteed minimal return on investment, this is a sensible rate of return to expect.",
    savingsRate: 'This is how much of your salary as a percentage you put aside. In the long run, this makes a much bigger difference than the amount of money you start with. Try playing around with savings and savings rate to see the difference!',
    debt: "Although your current debt may seem like a lot, what matters most is how much you manage to put aside to pay it off in regular installments.",
    debtRepayment: "Debt repayment: note that after your debt is repaid, any leftover payments go into savings. Therefore, assume that by the time you're reaching the age of retirement, your debts have been paid off and your savings rate is the sum of your savings and debt repayment rates. Because the interest you incurr on your debts and the interest you gain on your investments are usually different, playing around with these parameters can have interesting consequences.",
    debtInterest: "This is the interest on your debt. Sometimes it's possible to consolidate debt and get a better rate. It's always worth shopping around to see if you can refinance your debt. Play around with this parameter and see the difference one or two percentage points can make.",
    gradDate: "Although your graduation date affects how soon you'll be earning a salary, it may not make as big of a difference as you think.",
    retirementAge: "As humans live longer, healthier lives, there may be reason to rethink our retirement age. We've set it to 65 as a default, but have a look at the difference 2 or 3 years can make.",
    income: "This income was generated by the average salary for the occupation you chose. You can play around with this parameter if you think you have more detailed information on the type of salary you can expect to make in your chose career path.",

};

export default blurbs;